% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Group Assignment 1},
  pdfauthor={Alex Wong, Chelaka Paranahewa, Harjot Channa, Jonas Tiong},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Group Assignment 1}
\author{Alex Wong, Chelaka Paranahewa, Harjot Channa, Jonas Tiong}
\date{}

\begin{document}
\maketitle

\#Question 1

\hypertarget{a}{%
\subsection{1(a)}\label{a}}

\begin{enumerate}
\def\labelenumi{(\roman{enumi})}
\tightlist
\item
  Histogram of \texttt{logsal}
\end{enumerate}

\includegraphics{assignment_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{enumerate}
\def\labelenumi{(\roman{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

\begin{longtable}[]{@{}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0580}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1304}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1304}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1304}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1304}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1449}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1304}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1449}}@{}}
\toprule
\begin{minipage}[b]{\linewidth}\raggedleft
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
median
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
max
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
sd
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
skew
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
kurtosis
\end{minipage} \\
\midrule
\endhead
474 & 10.35679 & 10.27073 & 9.664596 & 11.81303 & 0.3973342 & 0.994876 &
0.6471944 \\
\bottomrule
\end{longtable}

As the mean is greater than the median, the distribution is positively
skewed indicating that there are high valued outliers (those earning
high annual wages). Since the skewness is 0.99, we can say that this
distribution is moderately skewed.

On average, an individual in this bank will have a log of annual salary
of around 10.36 or, in other words, an annual salary of around
\(e^{10.36} = 31,470.09\). The maximum annual salary, empirically, is
around \(e^{11.81} = 135,000.00\) and the lowest salary in the bank is
around \(e^{9.66} = 15,750.00\) That is a difference of around
\(119,250.00\).

\hypertarget{b}{%
\subsection{1(b)}\label{b}}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\tightlist
\item
\end{enumerate}

Scatterplot of \texttt{logsal} and \texttt{race}
\includegraphics{assignment_files/figure-latex/unnamed-chunk-4-1.pdf}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

Recall from part (a)ii) that the mean of \texttt{logsal} was around
10.36. From the scatterplot it is evident that in this bank, an
individual who does not belong to an ethnic minority earns in a wide
range of salaries from slightly below to 10.0 to slightly above 11.0 (as
per where all the data points are clustered). In contrast, for an
individual who does belong to an ethnic minority this is range is far
smaller, somewhere slightly below 10.0 to around 10.5. Hence, the gap
from the mean wage of 10.36 is larger for non-minorities which may
suggest larger mobility for this category of employees which would be
indicative of racial discrimination.

\hypertarget{c}{%
\subsection{1(c)}\label{c}}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\tightlist
\item
\end{enumerate}

\[
\hat{logsal} = \underset{(0.020)}{10.396} - \underset{(0.043)}{0.180} \ race
\]

\begin{verbatim}
## 
## Call:
## lm(formula = logsal ~ race, data = dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.73180 -0.27303 -0.06764  0.16623  1.41664 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 10.39639    0.02031 511.915  < 2e-16 ***
## race        -0.18049    0.04336  -4.163 3.74e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.3906 on 472 degrees of freedom
## Multiple R-squared:  0.03541,    Adjusted R-squared:  0.03337 
## F-statistic: 17.33 on 1 and 472 DF,  p-value: 3.737e-05
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# level of significance}
\NormalTok{alpha\_1 }\OtherTok{\textless{}{-}} \FloatTok{0.05}

\CommentTok{\# test statistic}
\NormalTok{tstat1 }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(fit1))[}\DecValTok{2}\NormalTok{, }\StringTok{"Estimate"}\NormalTok{] }\SpecialCharTok{/} 
  \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(fit1))[}\DecValTok{2}\NormalTok{, }\StringTok{"Std. Error"}\NormalTok{]}
\CommentTok{\# \textasciitilde{}t(472)}

\CommentTok{\# critical value under the null}
\NormalTok{tcrit1 }\OtherTok{\textless{}{-}} \FunctionTok{qt}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha\_1}\SpecialCharTok{/}\DecValTok{2}\NormalTok{, }\DecValTok{472}\NormalTok{)}

\CommentTok{\# decision}
\FunctionTok{abs}\NormalTok{(tstat1) }\SpecialCharTok{\textgreater{}}\NormalTok{ (tcrit1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#make something that says reject H0}
\end{Highlighting}
\end{Shaded}

In conclusion, at 0.05 level of significance, we reject the null
hypothesis that race has no effect on (the log of) an individual's
annual salary in favour of the alternative hypothesis race has an
effect.

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
\end{enumerate}

\(\hat{\beta_{1}}\) measures the average difference in the log of an
individual's annual salary in the bank (thus proportionate difference)
between someone who belongs to an ethnic minority and someone who does
not.

Hence, the average difference, according to our model, in an
individual's annual wage between someone who belongs to an ethnic
minority is \(e^{-0.180}\) times the annual salary of someone who does
not belong to an ethnic minority.

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
\end{enumerate}

This model does not provide conclusive evidence of racial discrimination
in salaries paid by the bank. This is because it does not account for
(condition on) confounding variables - variables that causally effect an
individual's annual salary and whether they belong to an ethnic
minority. For example, an individual's level of education may be a
variable of interest; the individual may be an immigrant to which US'
immigration policy and its skill stream for accepting immigrants (based
on education) may decide whether or not someone (in America) belongs to
an ethnic minority. And, for an individual's annual salary, may be
effected by if the company values (and thus willing to pay wages that
are higher) for someone based on the education that they have.

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{21}
\tightlist
\item
\end{enumerate}

As the coefficient of determination is around \(R = 0.035\), this means
that around 3.5 per cent of the sample variation in the log of an
individual's annual salary is explained by race in this bank. Hence,
this model is a very low fit for describing what variables effect an
individual's annual salary, where the remaining 96.5 per cent may be
caused be unaccounted for variables like education (as aforementioned)
or inherent variability.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SSR1 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{resid}\NormalTok{(fit1)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{SST1 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{((dat}\SpecialCharTok{$}\NormalTok{logsal }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{logsal))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}

\NormalTok{R2\_1 }\OtherTok{\textless{}{-}} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ (SSR1)}\SpecialCharTok{/}\NormalTok{SST1}
\NormalTok{R2\_1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.03541368
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{5}
\tightlist
\item
\end{enumerate}

\(\beta_{0}\) measures the conditional mean of the log of an
individual's annual salary in this bank who does not belong to an ethnic
minority. This value is 10.396. In other words, the conditional mean of
an individual's annual salary who is not part of of ethnic minority is
\(e^{10.396}\).

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{6}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LB1 }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(fit1))[}\DecValTok{1}\NormalTok{, }\StringTok{"Estimate"}\NormalTok{] }\SpecialCharTok{{-}} 
  \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(fit1))[}\DecValTok{1}\NormalTok{, }\StringTok{"Std. Error"}\NormalTok{] }\SpecialCharTok{*} \FunctionTok{qt}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha\_1}\SpecialCharTok{/}\DecValTok{2}\NormalTok{, }\DecValTok{472}\NormalTok{)}

\NormalTok{UP1 }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(fit1))[}\DecValTok{1}\NormalTok{, }\StringTok{"Estimate"}\NormalTok{] }\SpecialCharTok{+} 
  \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(fit1))[}\DecValTok{1}\NormalTok{, }\StringTok{"Std. Error"}\NormalTok{] }\SpecialCharTok{*} \FunctionTok{qt}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha\_1}\SpecialCharTok{/}\DecValTok{2}\NormalTok{, }\DecValTok{472}\NormalTok{)}

\NormalTok{confint1 }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(LB1, UP1) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{as.tibble}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{rename}\NormalTok{(}\StringTok{"2.5 \%"} \OtherTok{=}\NormalTok{ LB1,}
         \StringTok{"97.5 \%"} \OtherTok{=}\NormalTok{ UP1)}

\NormalTok{confint1 }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{kable}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}rr@{}}
\toprule
2.5 \% & 97.5 \% \\
\midrule
\endhead
10.35649 & 10.4363 \\
\bottomrule
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#confint(fit1, level = 0.95)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{7}
\tightlist
\item
\end{enumerate}

We are 95 per cent confident, on average, that the population value of
the the log of an individual's annual salary in this bank for someone
who does not belong to an ethnic minority is between 10.356 and 10.436.
That is, the population value of an individual's annual salary in this
bank is between \(e^{10.356}\) and \(e^{10.436}\), on average 95 per
cent of the time.

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{8}
\tightlist
\item
\end{enumerate}

Since \(\beta_{0} = 0\), in a hypothesis test of individual significance
at 0.05, does not fall within the 95 per cent confidence interval
\({10.356, 10.436}\) we conclude that \(\hat{\beta_{0}}\) is
statistically significant.

\hypertarget{d}{%
\subsection{1(d)}\label{d}}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\tightlist
\item
\end{enumerate}

\[
\hat{logsal} = \underset{(0.390)}{4.026} - \underset{(0.004)}{0.024} \ educ \ 
 + \ \underset{(0.045)}{0.601} \ logssal \ + \ \underset{(0.019)}{0.061} \ 
 gender \ - \ \underset{(0.019)}{0.043} \ race \ + \ \underset{(0.016)}{0.121} 
 \ jobcat
\]

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# OLS regression}
\NormalTok{fit2 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(logsal }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ logssal }\SpecialCharTok{+}\NormalTok{ gender }\SpecialCharTok{+}\NormalTok{ race }\SpecialCharTok{+}\NormalTok{ jobcat, }\AttributeTok{data =}\NormalTok{ dat)}
\NormalTok{fit2 }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{summary}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = logsal ~ educ + logssal + gender + race + jobcat, 
##     data = dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.41156 -0.11677 -0.01430  0.09835  0.91176 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  4.025756   0.390102  10.320  < 2e-16 ***
## educ         0.024382   0.003653   6.675 7.01e-11 ***
## logssal      0.600624   0.044518  13.492  < 2e-16 ***
## gender       0.060849   0.018852   3.228  0.00134 ** 
## race        -0.042609   0.019187  -2.221  0.02685 *  
## jobcat       0.120894   0.015717   7.692 8.65e-14 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.1666 on 468 degrees of freedom
## Multiple R-squared:  0.8261, Adjusted R-squared:  0.8242 
## F-statistic: 444.6 on 5 and 468 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

A regressor is individually insignificant at 0.001 level of significance
if its p-value is larger than 0.001, \(\textrm{p-value} > 0.001\). So,
according to our model only gender and race are individually
insignificant at this level as
\(\textrm{p-value}_{gender} = 0.0013 > 0.001\) and
\(\textrm{p-value}_{race} = 0.027 > 0.001\), respectively.

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# level of significance}
\NormalTok{alpha\_2 }\OtherTok{\textless{}{-}} \FloatTok{0.05}

\CommentTok{\# unrestricted model}
\NormalTok{fit2.UR }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(logsal }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ logssal }\SpecialCharTok{+}\NormalTok{ gender }\SpecialCharTok{+}\NormalTok{ race }\SpecialCharTok{+}\NormalTok{ jobcat, }\AttributeTok{data =}\NormalTok{ dat)}

\CommentTok{\# restricted model}
\NormalTok{fit2.R }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(logsal }\SpecialCharTok{\textasciitilde{}}\NormalTok{ logsal, }\AttributeTok{data =}\NormalTok{ dat)}

\CommentTok{\# Sum of squared residuals}
\NormalTok{SSR2.UR }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{resid}\NormalTok{(fit2.UR)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{SSR2.R }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{resid}\NormalTok{(fit2.R)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}

\CommentTok{\# degrees of freedom}
\NormalTok{DF2\_num }\OtherTok{\textless{}{-}} \FunctionTok{df.residual}\NormalTok{(fit2.R) }\SpecialCharTok{{-}} \FunctionTok{df.residual}\NormalTok{(fit2.UR) }\CommentTok{\#no. of restrictions = 5}
\NormalTok{DF2\_denom }\OtherTok{\textless{}{-}} \FunctionTok{df.residual}\NormalTok{(fit2.UR) }\CommentTok{\#degrees of freedom of UR linear model = 468}

\CommentTok{\# test statistic}
\NormalTok{tstat2 }\OtherTok{\textless{}{-}}\NormalTok{ ((SSR2.R }\SpecialCharTok{{-}}\NormalTok{ SSR2.UR) }\SpecialCharTok{/}\NormalTok{ DF2\_num) }\SpecialCharTok{/}\NormalTok{ ((SSR2.UR) }\SpecialCharTok{/}\NormalTok{ DF2\_denom)}
\CommentTok{\# \textasciitilde{} F(5, 468)}

\CommentTok{\# critical value}
\NormalTok{fcrit2 }\OtherTok{\textless{}{-}} \FunctionTok{qf}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha\_2}\SpecialCharTok{/}\DecValTok{2}\NormalTok{, DF2\_num, DF2\_denom)}

\CommentTok{\# decision}
\NormalTok{tstat2 }\SpecialCharTok{\textgreater{}}\NormalTok{ fcrit2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

In conclusion, at 0.05 level of significance, we reject the null
hypothesis that an individual's number of years of education, their
gender, the job category within the bank, their log of their starting
annual salary, and if they belong to an ethnic minority are jointly
insignificant in effecting (the log of an) individual's annual salary in
favour of the alternative hypothesis that at least one of these
variables are significant.

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
\end{enumerate}

\(\hat{\beta_{4}}\) measures the average difference in the log of an
individual's annual salary in the bank (thus proportionate difference)
between someone who belongs to an ethnic minority and someone who does
not, controlling for the the number of years of education, the gender,
the job category within the bank, and the log of an individual's
starting salary.

Hence, \emph{this} average difference, according to our model, for an
individual who belongs to an ethnic minority is \(e^{-0.043}\) times the
annual salary of someone who does not belong an ethnic minority.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{21}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(fit2))[}\DecValTok{4}\NormalTok{, }\StringTok{"Estimate"}\NormalTok{] }\SpecialCharTok{{-}} \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(fit2))[}\DecValTok{5}\NormalTok{, }\StringTok{"Estimate"}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1034585
\end{verbatim}

*****MATHSPEAK LATER

\(\hat{\beta_{3}} - \hat{\beta_{4}} = 0.103\) does not have a meaningful
interpretation. This is because \(\hat{\beta_{3}}\) is the conditional
mean of the log of an individual's annual salary given that they are
male and ceteris paribus minus the conditional mean of the log of an
individual's annual salary given that they are female and ceteris
paribus. \(\hat{\beta_{4}}\) is the conditional mean of the log an
individual's annual salary given that they belong to an ethnic minority
and ceteris paribus minus the conditional mean of the log of an
individual's annual salary given that the do not belong to an ethnic
minority and ceteris paribus. Hence, the difference between
\(\hat{\beta_{3}}\) and \(\hat{\beta_{4}}\) is the sum of the
conditional mean of an individual's annual salary given that they are
male, ceteris paribus (including one's racial status), plus the salary
given that they are not part of the ethnic minority, ceteris paribus
(including one's gender), minus the salary given that they are female,
ceteris paribus (including one's racial status), minus the salary given
that they are part of an ethnic minority, ceteris paribus (including
one's gender). The fact that this sum of different means is conditional
on different set of variables makes any descriptive application
inapplicable to the bank.

\begin{enumerate}
\def\labelenumi{(\roman{enumi})}
\setcounter{enumi}{5}
\tightlist
\item
\end{enumerate}

It is likely that this model does provide conclusive evidence of racial
discrimination in salaries paid by the bank, as per the individual
significance of the regression coefficient for \texttt{race} and the
joint significance of all regressors. This is because the model takes
into account possible confounding variables to \texttt{race} and
\texttt{logsal} --- years of education, one's gender, the job category,
and the (log of) starting salary --- which would allow us to make causal
statements about an individual's racial status on the (log of their)
annual salary. In other words, we are unlikely to have committed
\textbf{omitted variable bias} in this model by our specification of
variables.

\begin{enumerate}
\def\labelenumi{(\roman{enumi})}
\setcounter{enumi}{6}
\tightlist
\item
\end{enumerate}

The new model has \(R^{2} = 0.826\), meaning around 82.6 per cent of the
sample variation in the log of an individual's annual salary is
explained by the independent variables. This is a much better comparison
to the old model where only 3.5 per cent was explained by the
independent variables, leaving much variation unexplained (about a
\((0.826 - 0.035) \times 100\% = 79.1 \%\) difference).

Moreover, given that the variance inflation factor (VIF) is not more
than 10, which would be indicative of high correlation between
regressors, but rather very small at below 2 for each, this suggests
that our new model has not overspecified and that this \(R^{2}\) is not
high largely because of adding more variables.

\begin{longtable}[]{@{}lr@{}}
\toprule
Model & R-Squared \\
\midrule
\endhead
Old & 0.0354137 \\
New & 0.8261007 \\
\bottomrule
\end{longtable}

\begin{longtable}[]{@{}r@{}}
\toprule
VIF \\
\midrule
\endhead
1.892869 \\
4.205978 \\
1.505895 \\
1.077052 \\
2.517574 \\
\bottomrule
\end{longtable}

\hypertarget{e}{%
\subsection{1(e)}\label{e}}

We are working with the same model prior:

\[
\hat{logsal} = \underset{(0.390)}{4.026} - \underset{(0.004)}{0.024} \ educ \ 
 + \ \underset{(0.045)}{0.601} \ logssal \ + \ \underset{(0.019)}{0.061} \ 
 gender \ - \ \underset{(0.019)}{0.043} \ race \ + \ \underset{(0.016)}{0.121} 
 \ jobcat
\]

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# level of significance}
\NormalTok{alpha\_3 }\OtherTok{\textless{}{-}} \FloatTok{0.1}

\CommentTok{\# unrestricted model}
\NormalTok{fit3.UR }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(logsal }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ logssal }\SpecialCharTok{+}\NormalTok{ gender }\SpecialCharTok{+}\NormalTok{ race }\SpecialCharTok{+}\NormalTok{ jobcat, }\AttributeTok{data =}\NormalTok{ dat)}

\CommentTok{\# restricted model}
\NormalTok{fit3.R }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(logsal }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ logssal }\SpecialCharTok{+}\NormalTok{ jobcat, }\AttributeTok{data =}\NormalTok{ dat)}

\CommentTok{\# Sum of squared residuals}
\NormalTok{SSR3.UR }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{resid}\NormalTok{(fit3.UR)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{SSR3.R }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{resid}\NormalTok{(fit3.R)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}

\CommentTok{\# degrees of freedom}
\NormalTok{DF3\_num }\OtherTok{\textless{}{-}} \FunctionTok{df.residual}\NormalTok{(fit3.R) }\SpecialCharTok{{-}} \FunctionTok{df.residual}\NormalTok{(fit3.UR) }\CommentTok{\#no. of restrictions = 2}
\NormalTok{DF3\_denom }\OtherTok{\textless{}{-}} \FunctionTok{df.residual}\NormalTok{(fit3.UR) }\CommentTok{\#degrees of freedom of UR linear model = 468}

\CommentTok{\# test statistic}
\NormalTok{tstat3 }\OtherTok{\textless{}{-}}\NormalTok{ ((SSR3.R }\SpecialCharTok{{-}}\NormalTok{ SSR3.UR) }\SpecialCharTok{/}\NormalTok{ DF3\_num) }\SpecialCharTok{/}\NormalTok{ ((SSR3.UR) }\SpecialCharTok{/}\NormalTok{ DF3\_denom)}
\CommentTok{\# \textasciitilde{} F(2, 468)}

\CommentTok{\# critical value}
\NormalTok{fcrit3 }\OtherTok{\textless{}{-}} \FunctionTok{qf}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha\_3}\SpecialCharTok{/}\DecValTok{2}\NormalTok{, DF3\_num, DF3\_denom)}

\CommentTok{\# decision}
\NormalTok{tstat3 }\SpecialCharTok{\textgreater{}}\NormalTok{ fcrit3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

In conclusion, at 0.05 level of significance, we reject the null
hypothesis that an individual's gender and whether they belong to ethnic
minority has no effect on the (log of their) annual salary in favour of
the alternative hypothesis that their gender and/or their race does
effect the individual's (log of their) annual salary.

\hypertarget{f}{%
\subsection{1(f)}\label{f}}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\tightlist
\item
\end{enumerate}

Given that \[
\mathbb{E}[logsal \mid educ, logssal, gender, race, jobcat] = \beta_{0} + \beta_{1} \ educ + \beta_{2} \ logssal + \beta_{3} \ gender + \beta_{4} \ race + \beta_{5} \ jobcat
\] then our estimated conditional mean has form: \[
\hat{\beta_{0}} + \hat{\beta_{1}} \ educ + \hat{\beta_{2}} \ logssal + 
\hat{\beta_{3}} \ gender + \hat{\beta_{4}} \ race + \hat{\beta_{5}} \ jobcat
\]

For population A, i.e.~for the population of female managers with 12
years of education who belong to a racial minority and received a given
starting salary, the average \texttt{logsal} is: \[
\mathbb{E}[logsal \mid educ = 12, gender = 0, race = 1, jobcat = 3, logssal] = 
\beta_{0} + \beta_{1}12 + \beta_{2} \ logssal + \beta_{4} 
+ \beta_{5}3 
\\
= (\beta_{0} + 12\beta_{1} + \beta_{4} + 3\beta_{5}) + \beta_{2} \ logssal
\]

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

Likewise, for population B, i.e.~for the population of male managers
with 11 years of education who are not members of a ethnic minority and
receives the same starting salary as the individuals in population A,
the average \texttt{logsal} is:

\[
\mathbb{E}[logsal \mid educ = 11, gender = 1, race = 0, jobcat = 3, logssal] = 
\beta_{0} + \beta_{1}11 + \beta_{2} \ logssal + \beta_{3} 
+ \beta_{5}3 
\\
= (\beta_{0} + 11\beta_{1} + \beta_{3} + 3\beta_{5}) + \beta_{2} \ logssal
\]

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
\end{enumerate}

Given the null hypothesis that the average \texttt{logsal} of population
A is equal to that of population B
\(\mathbb{E}[logsal \mid educ = 12, gender = 0, race = 1, jobcat = 3, logssal] = \mathbb{E}[logsal \mid educ = 11, gender = 1, race = 0, jobcat = 3, logssal]\),
it follows that:

\(\mathbb{E}[logsal \mid educ = 12, gender = 0, race = 1, jobcat = 3, logssal] - \mathbb{E}[logsal \mid educ = 11, gender = 1, race = 0, jobcat = 3, logssal] = 0\)

which is just: \$ (\beta\emph{\{0\} + 12\beta}\{1\} + \beta\emph{\{4\} +
3\beta}\{5\}) + \beta\emph{\{2\} ~logssal - (\beta}\{0\} +
11\beta\emph{\{1\} + \beta}\{3\} + 3\beta\emph{\{5\}) - \beta}\{2\}
~logssal = \beta\emph{\{1\} + \beta}\{4\} - \beta\_\{3\} = 0\$

So the restriction that follows from the null hypothesis is that
\(\beta_{1} + \beta_{4} = \beta_{3}\). The negation of this statement is
that \(\beta_{1} + \beta_{4} \neq \beta_{3}\) which is the alternative
hypothesis, where the average \texttt{logsal} of population A is not
equal to that of population B.

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
\end{enumerate}

Under the null hypothesis, \(\beta_{1} + \beta_{4} = \beta_{3}\). So,
rearranging to get \(\beta_{1} = \beta_{3} - \beta_{4}\) we can
substitute this into our unrestricted model (the population model):

\[
\mathbb{E}[logsal \mid educ, logssal, gender, race, jobcat] = \beta_{0} + 
\beta_{1} \ educ + \beta_{2} \ logssal + \beta_{3} \ gender + \beta_{4} \ race 
+ \beta_{5} \ jobcat
\]

to get:

\$\$ \beta\emph{\{0\} + (\beta}\{3\} - \beta\emph{\{4\}) ~educ +
\beta}\{2\} ~logssal + \beta\emph{\{3\} ~gender + \beta}\{4\} ~race +
\beta\_\{5\} ~jobcat

\textbackslash{}

= \beta\emph{\{0\} + \beta}\{3\} ~educ - \beta\emph{\{4\} ~educ +
\beta}\{2\} ~logssal + \beta\emph{\{3\} ~gender + \beta}\{4\} ~race +
\beta\_\{5\} ~jobcat

\textbackslash{}

= \beta\emph{\{0\} + \beta}\{2\}(educ ~+ ~logssal) + \beta\emph{\{3\}
~gender + \beta}\{4\}(race ~- ~educ) + \beta\_\{5\} ~jobcat \$\$ let
\(U = educ + logssal\) and \(V = race - educ\), so

\[
\beta_{0} + \beta_{2}U + \beta_{3} \ gender + \beta_{4}V + \beta_{5} \ jobcat
\] This expression is our restricted model. We will use these two models
for our F-test when we come to test the null hypothesis that
\(\beta_{1} + \beta_{4} = \beta_{3}\) (tantamount to holding that the
two populations A and B have the same \texttt{logsal}) against the
alternative hypothesis that \(\beta_{1} + \beta_{4} \neq \beta_{3}\)
(that the two populations A and B do not have the same average
\texttt{logsal}).

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{21}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#fit4.UR \textless{}{-} lm(logsal \textasciitilde{} educ + logssal + gender + race + jobcat, data = dat)}

\NormalTok{U }\OtherTok{\textless{}{-}}\NormalTok{ dat}\SpecialCharTok{$}\NormalTok{educ }\SpecialCharTok{{-}}\NormalTok{ dat}\SpecialCharTok{$}\NormalTok{logssal}
\NormalTok{V }\OtherTok{\textless{}{-}}\NormalTok{ dat}\SpecialCharTok{$}\NormalTok{race }\SpecialCharTok{{-}}\NormalTok{ dat}\SpecialCharTok{$}\NormalTok{educ}

\NormalTok{fit4.R }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(logsal }\SpecialCharTok{\textasciitilde{}}\NormalTok{ U }\SpecialCharTok{+}\NormalTok{ gender }\SpecialCharTok{+}\NormalTok{ V }\SpecialCharTok{+}\NormalTok{ jobcat, }\AttributeTok{data =}\NormalTok{ dat)}

\NormalTok{fit4.R }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{summary}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = logsal ~ U + gender + V + jobcat, data = dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.46457 -0.12666 -0.01398  0.12058  0.85875 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  8.28172    0.16386  50.541  < 2e-16 ***
## U           -0.12024    0.01994  -6.029 3.34e-09 ***
## gender       0.16001    0.01916   8.353 7.57e-16 ***
## V           -0.16023    0.01860  -8.615  < 2e-16 ***
## jobcat       0.22745    0.01459  15.595  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.1893 on 469 degrees of freedom
## Multiple R-squared:  0.7749, Adjusted R-squared:  0.773 
## F-statistic: 403.6 on 4 and 469 DF,  p-value: < 2.2e-16
\end{verbatim}

So our restricted model is: \[
\hat{logsal} = \underset{(0.164)}{8.282} - \underset{(0.020)}{0.120}U + 
\underset{(0.019)}{0.160} \ gender \ - \underset{(0.019)}{0.160}V + 
\underset{(0.015)}{0.227} \ jobcat
\]

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{5}
\tightlist
\item
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# level of significance}
\NormalTok{alpha\_4 }\OtherTok{\textless{}{-}} \FloatTok{0.1}

\CommentTok{\# unrestricted model}
\NormalTok{fit4.UR }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(logsal }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ logssal }\SpecialCharTok{+}\NormalTok{ gender }\SpecialCharTok{+}\NormalTok{ race }\SpecialCharTok{+}\NormalTok{ jobcat, }\AttributeTok{data =}\NormalTok{ dat)}

\CommentTok{\# Sum of squared residuals}
\NormalTok{SSR4.UR }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{resid}\NormalTok{(fit4.UR)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{SSR4.R }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{resid}\NormalTok{(fit4.R)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}

\CommentTok{\# degrees of freedom}
\NormalTok{DF4\_num }\OtherTok{\textless{}{-}} \FunctionTok{df.residual}\NormalTok{(fit4.R) }\SpecialCharTok{{-}} \FunctionTok{df.residual}\NormalTok{(fit4.UR) }\CommentTok{\#no. of restrictions = 1 }
\NormalTok{DF4\_denom }\OtherTok{\textless{}{-}} \FunctionTok{df.residual}\NormalTok{(fit4.UR) }\CommentTok{\#degrees of freedom of UR linear model = 468}

\CommentTok{\# test statistic}
\NormalTok{tstat4 }\OtherTok{\textless{}{-}}\NormalTok{ ((SSR4.R }\SpecialCharTok{{-}}\NormalTok{ SSR4.UR) }\SpecialCharTok{/}\NormalTok{ DF4\_num) }\SpecialCharTok{/}\NormalTok{ ((SSR4.UR) }\SpecialCharTok{/}\NormalTok{ DF4\_denom)}
\CommentTok{\# \textasciitilde{} F(1, 468)}

\CommentTok{\# critical value}
\NormalTok{fcrit4 }\OtherTok{\textless{}{-}} \FunctionTok{qf}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha\_4}\SpecialCharTok{/}\DecValTok{2}\NormalTok{, DF4\_num, DF4\_denom)}

\CommentTok{\# decision}
\NormalTok{tstat4 }\SpecialCharTok{\textgreater{}}\NormalTok{ fcrit4}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

In conclusion, at 0.05 level of significance, we reject the null
hypothesis that the average of the \texttt{logsalary} for population A
is the same population B in favour of the alternative hypothesis that
they are not equal. In other words, there is a difference between an
individual who is female, a manager, with 12 years of education, belongs
to an ethnic minority, and has a starting salary \emph{and} an
individual who is male, a manager, has 11 years of education, is not an
member of a ethnic minority, and also has a starting salary.

\hypertarget{g}{%
\subsection{1(g)}\label{g}}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\tightlist
\item
\end{enumerate}

By definition, the racial pay gap for males is: \[
\mathbb{E}[logsal \mid gender = 1, race =1, educ, logssal, jobcat] - \mathbb{E}[logsal \mid gender = 1, race = 0, educ, logssal, jobcat]
\]

Given \[
\mathbb{E}[logsal \mid educ, logssal, gender, race, jobcat] = \beta_{0} + \beta_{1} \ educ + \beta_{2} \ logssal + \beta_{3} \ gender + \beta_{4} \ race + \beta_{5} \ jobcat
\] it follows that:

\$\$ \mathbb{E}{[}logsal \mid gender = 1, race =1, educ, logssal,
jobcat{]} - \mathbb{E}{[}logsal \mid gender = 1, race = 0, educ,
logssal, jobcat{]}

\textbackslash{}

= \beta\emph{\{0\} + \beta}\{1\} ~educ + \beta\emph{\{2\} ~logssal +
\beta}\{3\} + \beta\emph{\{4\} + \beta}\{5\} ~jobcat - (\beta\emph{\{0\}
+ \beta}\{1\} ~educ + \beta\emph{\{2\} ~logssal + \beta}\{3\} +
\beta\_\{5\} ~jobcat)

\textbackslash{}

= \beta\_\{4\} \$\$ So the racial pay gap for males is \(\beta_{4}\).

\begin{enumerate}
\def\labelenumi{(\roman{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  By definition, the racial pay gap for females is: \[
  \mathbb{E}[logsal \mid gender = 0, race =1, educ, logssal, jobcat] - \mathbb{E}[logsal \mid gender = 0, race = 0, educ, logssal, jobcat
  \] Given \[
  \mathbb{E}[logsal \mid educ, logssal, gender, race, jobcat] = \beta_{0} + \beta_{1} \ educ + \beta_{2} \ logssal + \beta_{3} \ gender + \beta_{4} \ race + \beta_{5} \ jobcat
  \] it follows that:
\end{enumerate}

\$\$ \mathbb{E}{[}logsal \mid gender = 0, race =1, educ, logssal,
jobcat{]} - \mathbb{E}{[}logsal \mid gender = 0, race = 0, educ,
logssal, jobcat{]}

\textbackslash{}

= \beta\emph{\{0\} + \beta}\{1\} ~educ + \beta\emph{\{2\} ~logssal +
\beta}\{4\} + \beta\emph{\{5\} ~jobcat - (\beta}\{0\} + \beta\emph{\{1\}
~educ + \beta}\{2\} ~logssal + \beta\_\{5\} ~jobcat)

\textbackslash{}

= \beta\_\{4\} \$\$ So the racial pay gap for females is also
\(\beta_{4}\).

These results make sense, for another interpretation of \(\beta_{4}\) is
the partial effect of being in an ethnic minority on the log of an
individual's starting salary against not being in an ethnic minority,
that is, holding all else constant. Hence, whether or not we are looking
at male or female racial pay gap is already accounted for in this model
by \(\beta_{4}\).

\hypertarget{h}{%
\subsection{1(h)}\label{h}}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\tightlist
\item
\end{enumerate}

To allow in our model for the racial pay gap to vary by gender, we may
introduce the interaction term \(race \times gender\), allowing
\texttt{race} to vary as a function of \texttt{gender}. Thus,

\[
\mathbb{E}[logsal \mid educ, logssal, gender, race, jobcat] = \beta_{0} + \beta_{1} \ educ + \beta_{2} \ logssal + \beta_{3} \ gender + \beta_{4} \ race + \beta_{5} \ jobcat + \beta_{6} \ race \times gender
\] ii)

The racial pay gap for males, controlling for education, starting
salary, and job category is: \[
\mathbb{E}[logsal \mid gender = 1, race =1, educ, logssal, jobcat] - \mathbb{E}[logsal \mid gender = 1, race = 0, educ, logssal, jobcat]
\] According to our new model, this is

\$\$ \mathbb{E}{[}logsal \mid gender = 1, race =1, educ, logssal,
jobcat{]} - \mathbb{E}{[}logsal \mid gender = 1, race = 0, educ,
logssal, jobcat{]}

\textbackslash{}

= \beta\emph{\{0\} + \beta}\{1\} ~educ + \beta\emph{\{2\} ~logssal +
\beta}\{3\} + \beta\emph{\{4\} + \beta}\{5\} ~jobcat + \beta\emph{\{6\}
- (\beta}\{0\} + \beta\emph{\{1\} ~educ + \beta}\{2\} ~logssal +
\beta\emph{\{3\} + \beta}\{5\} ~jobcat)

\textbackslash{}

= \beta\emph{\{4\} + \beta}\{6\} \$\$

So \emph{this} racial pay gap for males is equal to
\(\beta_{4} + \beta_{6}\).

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
\end{enumerate}

The racial pay grap for females, controlling for education, starting
salary, and job category is: \[
\mathbb{E}[logsal \mid gender = 0, race =1, educ, logssal, jobcat] - \mathbb{E}[logsal \mid gender = 0, race = 0, educ, logssal, jobcat]
\] According to our new model, this is

\$\$ \mathbb{E}{[}logsal \mid gender = 0, race =1, educ, logssal,
jobcat{]} - \mathbb{E}{[}logsal \mid gender = 0, race = 0, educ,
logssal, jobcat{]}

\textbackslash{}

= \beta\emph{\{0\} + \beta}\{1\} ~educ + \beta\emph{\{2\} ~logssal +
\beta}\{4\} + \beta\emph{\{5\} ~jobcat - (\beta}\{0\} + \beta\emph{\{1\}
~educ + \beta}\{2\} ~logssal + \beta\_\{5\} ~jobcat)

\textbackslash{}

= \beta\_\{4\} \$\$

So \emph{this} racial pay gap for females is equal to \(\beta_{4}\).

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
\end{enumerate}

The null hypothesis is that, controlling for education, starting salary,
and job category, the racial pay gap for males and females is the same.
Hence, from part (h)ii) and part (h)iii) this statement is equivalent to
the stating that \(\beta_{4} + \beta{6} = \beta_{4}\) which in other
words is to say that \(\beta_{6} = 0\).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# level of significance}
\NormalTok{alpha\_5 }\OtherTok{\textless{}{-}} \FloatTok{0.1}

\CommentTok{\# OLS regression}
\NormalTok{fit5 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(logsal }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ logssal }\SpecialCharTok{+}\NormalTok{ gender }\SpecialCharTok{+}\NormalTok{ race }\SpecialCharTok{+}\NormalTok{ jobcat }\SpecialCharTok{+}\NormalTok{ race}\SpecialCharTok{*}\NormalTok{gender, }
           \AttributeTok{data =}\NormalTok{ dat)}

\CommentTok{\# test statistic}
\NormalTok{tstat5 }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(fit5))[}\DecValTok{7}\NormalTok{, }\StringTok{"Estimate"}\NormalTok{] }\SpecialCharTok{/} 
  \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(fit5))[}\DecValTok{7}\NormalTok{, }\StringTok{"Std. Error"}\NormalTok{]}
\CommentTok{\# \textasciitilde{}t(467)}

\CommentTok{\# critical value under the null}
\NormalTok{tcrit5 }\OtherTok{\textless{}{-}} \FunctionTok{qt}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ alpha\_5}\SpecialCharTok{/}\DecValTok{2}\NormalTok{, }\DecValTok{467}\NormalTok{)}

\CommentTok{\# decision}
\FunctionTok{abs}\NormalTok{(tstat5) }\SpecialCharTok{\textgreater{}}\NormalTok{ tcrit5}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] FALSE
\end{verbatim}

In conclusion, at 0.10 level of significance, we reject the null
hypothesis that, controlling for education, starting salary, and job
category, the racial pay gap for males and females is the same in favour
of the alternative hypothesis that they are not.

\end{document}
