---
title: "ETC2410 Assignment 2"
author: "Alex Wong, Chelaka Paranahewa, Harjot Channa, Jonas Tiong"
head-includes:
    - \usepackage{mathtools}
output: 
    pdf_document:
        df_print: kable
    latex_engine: xelatex
mainfont: Times New Roman
fontsize: 12pt
---

# **Question 2 (31 Marks)**

```{r Setup, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE}
library(tidyverse)
library(fpp3)
library(knitr)

knitr::opts_chunk$set(
    echo = FALSE,
    warning = FALSE,
    error = FALSE,
    message = FALSE
)

db <- read.csv2(
    file = "Assignment 2/Data/HOUSTNSA.csv",
    sep = ","
)

db <- db %>%
    as_tibble() %>%
    mutate(
        DATE = yearmonth(DATE),
        HOUSTNSA = as.numeric(HOUSTNSA)
    ) %>%
    as_tsibble()

db$Jan <- ifelse(month(db$DATE) == 1, 1, 0)
db$Feb <- ifelse(month(db$DATE) == 2, 1, 0)
db$Mar <- ifelse(month(db$DATE) == 3, 1, 0)
db$Apr <- ifelse(month(db$DATE) == 4, 1, 0)
db$May <- ifelse(month(db$DATE) == 5, 1, 0)
db$Jun <- ifelse(month(db$DATE) == 6, 1, 0)
db$Jul <- ifelse(month(db$DATE) == 7, 1, 0)
db$Aug <- ifelse(month(db$DATE) == 8, 1, 0)
db$Sep <- ifelse(month(db$DATE) == 9, 1, 0)
db$Oct <- ifelse(month(db$DATE) == 10, 1, 0)
db$Nov <- ifelse(month(db$DATE) == 11, 1, 0)
```

## 2(a)
```{r}
lmObj <- lm(
    HOUSTNSA ~ Jan + Feb + Mar + Apr +
        May + Jun + Jul + Aug + Sep + Oct + Nov,
    data = db
)
summary(lmObj)
```
<!-- Analysis -->
\begin {equation}
    \widehat{logsal} = \underset{(0.020)}{10.396} - \underset{(0.043)}{0.180} \ race
\end {equation}

## 2(b)
```{r}

```
<!-- Analysis -->

## 2(c)
```{r}

```
<!-- Analysis -->

## 2(d)
```{r}

```
<!-- Analysis -->

## 2(e)
```{r}

```
<!-- Analysis -->
